FROM golang:1.7.1-alpine

COPY . /go/src/uct

ENV APP_PACKAGE="uct/ein"
ENV APP_NAME="ein"

RUN apk update && \
    apk add ca-certificates && \
    update-ca-certificates && \
    apk add openssl && \
    apk add git && \
    wget https://github.com/Masterminds/glide/releases/download/v0.12.1/glide-v0.12.1-linux-amd64.tar.gz && \
    tar -xzf glide-v0.12.1-linux-amd64.tar.gz && \
    mv linux-amd64/glide /usr/bin && \
    cd /go/src/uct && \
    glide install && \
    go install -v ${APP_PACKAGE} && \
    rm -rf *.tar.gz* && \
    apk del git && \
    apk del openssl

WORKDIR /go/src/uct

ENTRYPOINT ["ein"]
EXPOSE 13100

CMD ["-c" , "/go/src/uct/common/config.toml", "-f", "protobuf"]