FROM golang:1.7

COPY . /go/src/uct


RUN curl -OL https://github.com/Masterminds/glide/releases/download/v0.12.1/glide-v0.12.1-linux-amd64.tar.gz && \
    tar -xzf glide-v0.12.1-linux-amd64.tar.gz && \
    mv linux-amd64/glide /usr/bin && \
    cd /go/src/uct && \
    glide install && \
    go install -v uct/servers/spike

WORKDIR /go/src/uct

ENTRYPOINT ["spike"]

CMD ["-c" , "common/config.toml"]