apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: monitoring
  name: edward
  labels:
    metrics: edward
spec:
  jobLabel: edward
  selector:
    matchLabels:
      app: edward
  namespaceSelector:
    matchNames:
    - staging
    - production
  endpoints:
  - port: metrics-port
    interval: 15s
    honorLabels: true
---
apiVersion: v1
kind: Service
metadata:
  namespace: staging
  name: edward
  labels:
    app: edward
    metrics: "true"
spec:
  selector:
    app: edward
  ports:
  - name: metrics-port
    port: 13000
    protocol: TCP
    targetPort: metrics-port
