FROM golang:1.9-alpine

COPY . /go/src/uct

ENV APP_PACKAGE="uct/scrapers/rutgers"
ENV APP_NAME="rutgers"

RUN apk --no-cache add ca-certificates openssl git && \
    update-ca-certificates && \
    go get -u github.com/golang/dep/cmd/dep && \
    cd /go/src/uct && \
    dep ensure && \
    apk del git openssl

RUN go install -v ${APP_PACKAGE}

WORKDIR /go/src/uct
EXPOSE 13302

ENTRYPOINT ["rutgers", "--daemon", "2m", "--latest", "-f" , "protobuf", "-c" , "/go/src/uct/common/conf/config.toml"]